#!/bin/bash

set -x

JAVA_HOME="/usr/java/default"
CATALINA_HOME="/usr/share/tomcat6"

######################################################################################
# General config and utils                                                           #
######################################################################################

yum -y install epel-release
yum -y install xmlstarlet wget

# includes /usr/sbin in non-login shells
echo '. /etc/profile' >> /home/jenkins/.bashrc

# open port 443 for web service
REJECT_RULE=`iptables -nL INPUT --line-numbers | grep REJECT | cut -d ' '  -f 1`
iptables -I INPUT ${REJECT_RULE} -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT
iptables-save > /etc/sysconfig/iptables
service iptables restart

######################################################################################
# Dependencies  (java + tomcat + httpd + shibboleth)                                 #
######################################################################################

# installing java 8
JAVA_LINK=`curl -s http://www.java.com/en/download/linux_manual.jsp 2>/dev/null | grep -m 1 'Linux x64 RPM'| cut -d '"' -f 4`
if [ -n $JAVA_LINK ]; then
        wget -q -O sun-java.rpm ${JAVA_LINK}
        rpm -iv sun-java.rpm
        echo "export JAVA_HOME=${JAVA_HOME}" >> /etc/bashrc
        echo 'export PATH=${JAVA_HOME}/bin:${PATH}' >> /etc/bashrc
else
        echo "Could not find the right JAVA_LINK"
        exit 1;
fi

# installing tomcat
yum -y install tomcat6
rm -rf ${CATALINA_HOME}/webapps/*
echo "export CATALINA_HOME=${CATALINA_HOME}" >> /etc/bashrc

# installing httpd
yum -y install httpd httpd-tools mod_ssl

######################################################################################
# Shibboleth                                                                         #
######################################################################################

wget -q -O /etc/yum.repos.d/shibboleth.repo \
     "http://download.opensuse.org/repositories/security:/shibboleth/CentOS_CentOS-6/security:shibboleth.repo"
yum -y makecache
yum -y install shibboleth

######################################################################################
# MyProxy                                                                            #
######################################################################################

yum -y install myproxy myproxy-server myproxy-admin myproxy-doc
yum -y install globus-simple-ca
