#!/bin/bash

set -x

JAVA_HOME="/usr/java/default"
CATALINA_HOME="/usr/share/tomcat6"

######################################################################################
# General config and utils                                                           #
######################################################################################

yum -y install xmlstarlet wget

# includes /usr/sbin in non-login shells
echo '. /etc/profile' >> /home/jenkins/.bashrc

#make sure domainname is set
domainname demo
hostname `hostname -s`.demo

######################################################################################
# Dependencies  (java + tomcat + httpd + shibboleth)                                 #
######################################################################################

# installing java 8
JAVA_LINK=`curl -s http://www.java.com/en/download/linux_manual.jsp 2>/dev/null | grep -m 1 'Linux x64 RPM'| cut -d '"' -f 4`

if [ -n $JAVA_LINK ]; then
        wget -q -O sun-java.rpm ${JAVA_LINK}
        rpm -iv sun-java.rpm
        echo "export JAVA_HOME=${JAVA_HOME}" >> /etc/bashrc
        echo 'export PATH=${JAVA_HOME}/bin:${PATH}' >> /etc/bashrc
else
        echo "Could not find the right JAVA_LINK"
        exit 1;
fi


# installing tomcat
yum -y install tomcat6
rm -rf ${CATALINA_HOME}/webapps/*
echo "export CATALINA_HOME=${CATALINA_HOME}" >> /etc/bashrc

# installing httpd
yum -y install httpd httpd-tools mod_ssl
