#!/bin/bash

set -x

JAVA_HOME="/usr/java/default"
CATALINA_HOME="/usr/share/tomcat"

TOMCAT_CONF="/etc/tomcat/tomcat.conf"
TOMCAT_CONF_DIR="${CATALINA_HOME}/conf"

SHIB_LATEST="http://shibboleth.net/downloads/identity-provider/latest/"
SHIB_INSTALL_DIR="/opt/shibboleth-idp"
SHIB_DIR="/opt/shibboleth-install"

######################################################################################
# General config and utils                                                           #
######################################################################################

yum -y install epel-release
yum -y install xmlstarlet wget

# includes /usr/sbin in non-login shells
echo '. /etc/profile' >> /home/jenkins/.bashrc

# include port 443 in firewall rules
firewall-cmd --zone=public --add-port=443/tcp --permanent
firewall-cmd --reload

######################################################################################
# Dependencies    (tomcat + java8)                                                   #
######################################################################################


# installing java 8
JAVA_LINK=`curl -s http://www.java.com/en/download/linux_manual.jsp 2>/dev/null | grep -m 1 'Linux x64 RPM'| cut -d '"' -f 4`
if [ -n $JAVA_LINK ]; then
        wget -q -O sun-java.rpm ${JAVA_LINK}
        rpm -iv sun-java.rpm
        echo "export JAVA_HOME=${JAVA_HOME}" >> /etc/bashrc
        echo 'export PATH=${JAVA_HOME}/bin:${PATH}' >> /etc/bashrc
else
        echo "Could not find the right JAVA_LINK"
        exit 1;
fi

# installing tomcat
yum -y install tomcat
rm -rf ${CATALINA_HOME}/webapps/*
echo "export CATALINA_HOME=${CATALINA_HOME}" >> /etc/bashrc

# make sure this install script will have all the right env variables
source /etc/bashrc

# install tomcat-jsvc and tweak tomcat so it can open ports < 1024 
# this is required by the shibboleth-idp (port 443)
yum -y install tomcat-jsvc
sed -i 's/^User=.*/#\&/'   /usr/lib/systemd/system/tomcat.service
sed -i 's/^Group=.*/#\&/'   /usr/lib/systemd/system/tomcat.service
#this might not work!!!
echo 'USE_JSVC=true' >> ${TOMCAT_CONF}
sed -i "s#^JAVA_HOME=.*#JAVA_HOME=\"${JAVA_HOME}\"#"  ${TOMCAT_CONF}


######################################################################################
# Shibboleth IdP                                                                     #
######################################################################################


# download and unpack shibboleth idp v3
SHIB_FILE=`curl -s ${SHIB_LATEST} | grep tar.gz\< | cut -d '"' -f 6`

if [ -n ${SHIB_FILE} ]; then
        wget -q -O ${SHIB_FILE} "${SHIB_LATEST}${SHIB_FILE}"
        mkdir ${SHIB_DIR}
        tar xzf ${SHIB_FILE} -C ${SHIB_DIR}
        mkdir ${SHIB_INSTALL_DIR}
else
        echo "Could not find the right SHIB_FILE"
        exit 1;
fi


######################################################################################
# LDAP Server                                                                        #
######################################################################################

yum -y install openldap openldap-clients openldap-servers

